#Кроль Данило
##ФІТ 2-16
##Варіант 10


In [ ]:
import numpy as np

#1.1.1
A = np.matrix(([1,  2],
               [4, -1]))

B = np.matrix(([ 2, -3],
               [-4,  1]))

C = np.dot(A, B) - np.dot(B, A)
print(C)

[[ 4 -8]
 [12 -4]]


In [ ]:
# 1.2.1

A = np.matrix(([-1, 2],
               [ 0, 1]))

print(np.dot(A, A))

[[1 0]
 [0 1]]


In [ ]:
# 1.3.1

A = np.matrix(([3,  5],
               [6, -1]))

B = np.matrix(([2,  1],
               [-3, 2]))

print(np.dot(A, B))

[[-9 13]
 [15  4]]


In [ ]:
# 1.4.5

A = np.matrix(([1, 5, -5],
               [4, 0, 3],
               [2, -10, 3]))
print(np.linalg.det(A))

200.0000000000001


In [ ]:
# 1.5.2

A = np.matrix(([2, 3, 4, 1],
               [1, 2, 3, 4],
               [3, 4, 1, 2],
               [4, 1, 2, 3]))
print(np.linalg.det(A))

-160.00000000000009


In [ ]:
# 1.6.2

A = np.matrix(([2,  5,  7],
               [6,  3,  4],
               [5, -2, -3]))
print(np.linalg.inv(A))

[[  1.  -1.   1.]
 [-38.  41. -34.]
 [ 27. -29.  24.]]


In [ ]:
# 1.7.3

A = np.matrix(([-2, 3, 1, -1],
               [ 3, 2, 1,  4],
               [ 1, 2, 3,  4],
               [ 0, 2, 3,  3]))

print(np.linalg.matrix_rank(A))


3


In [ ]:
# 1.8.10

A = np.matrix(([3,  2, 1],
               [2, -1, 1],
               [1,  5, 0]))

B = np.array([5, 6, -3])

# Матричний метод
inv = np.linalg.inv(A)
ma = np.dot(inv, B)
print(f"Матричний метод:\n{ma}")

# Метод Крамера
det_c = np.linalg.det(A)
ans = []
for i in range(len(A)):
  Ac = np.copy(A)
  Ac[:, i] = B
  ans.append(round(np.linalg.det(Ac) / det_c, 1))
print(f"\nМетод Крамера:\n{ans}")

# Метод Гауса
Bc = np.copy(B).astype(float)
Ac = np.copy(A).astype(float)

reshaped_b = Bc.reshape((len(Bc), 1))
Ac = np.hstack((Ac, reshaped_b))

for i in range(len(Ac)):
  for j in range(i + 1, len(Ac)):
    Ac[j] -= Ac[i] * Ac[j][i] / Ac[i][i]

x = np.zeros(len(Bc))

i = len(Ac) - 1
while i >= 0:
    x[i] = (Ac[i][-1] - sum(x * Ac[i][0:-1])) / Ac[i][i]
    i -= 1

print(f"\nМетод Гауса:\n{x}")

Матричний метод:
[[ 2. -1.  1.]]

Метод Крамера:
[2.0, -1.0, 1.0]

Метод Гауса:
[ 2. -1.  1.]


In [ ]:
# 2.2
import random

def gen_array(n, m):
  ret = []
  for i in range(n):
    tmp = random.sample(range(-10, 10), m)
    ret.append(tmp)
  return ret

N = 5
M = 10

A = np.matrix((gen_array(N, M)))
print(A)

avg = []
for i in range(N):
  avg.append(np.sum(A[i])/M)
print(f"{avg=}")
print(f"{min(avg)=}")


[[  6  -7  -2   2   8   4   9 -10   0   7]
 [  4  -9 -10  -7   3   7  -2  -3   2  -5]
 [ -7  -2   1   3  -3  -4  -6  -9   5  -1]
 [  9  -9  -1   4  -2   6  -6   0  -3   8]
 [  9  -8   5   0   3   4   6   2  -6  -4]]
avg=[1.7, -2.0, -2.3, 0.6, 1.1]
min(avg)=-2.3
